highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /ashekchowdhury/
title: Chowdhury Ashek Bin Helal's Resume
name: Chowdhury Ashek Bin Helal
email: ashek.himu@gmail.com
email_full: mailto:ashek.himu@gmail.com
github: ashekchowdhury
linkedin: in/chowdhury-ashek-bin-helal-611010136/
tel: +358413688612
tel_full: tel:+358413688612
address:
  street: Maunulanmaki
  postcode: 00630
  city: Helsinki
  country: Finland

# needed for travis-ci build
exclude: [vendor]
